version: '3'

services:
  app:
    restart: always
    container_name: Aal 
    environment:
      - TZ=Asia/Makassar
    build:
      context: .
    ports:
      - "8020:8020"
    volumes:
      - .:/app
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8020 --workers 2