# Generated by Django 4.2.10 on 2024-06-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("berita", "0003_artikel_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="artikel",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
