# Generated by Django 4.2.10 on 2024-06-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pengguna", "0002_biodata_foto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biodata", options={"verbose_name_plural": "1. Biodata"},
        ),
    ]
